title: Network for Code
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://networkforcode.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: In√≠cio
    url: /index.html
  - title: Sobre
    url: /about
  - title: 
    url: /contact

social:
  github: networkforcode
  linkedin: https://www.linkedin.com/in/thiago-porfirio
  email: tiagutino.porfirio@gmail.com

google_analytics: ""
